### ISSUE TITLE
[FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by Kim-jisoo11** [29th-WE-SOPT-iOS-Part/KimJiSoo#7]
## 📌  Feature Issue

로그인, 회원가입 서버 연결하는 과제입니다.

## 📝  To-do

- [x] 로그인 서버 연결
- [ ] 회원가입 서버 연결
- [ ] 도전과제 - UserDefault 사용
